//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypicalSouthernFoods.Webforms.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAITER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAITER()
        {
            this.INVOICES = new HashSet<INVOICE>();
        }
    
        public decimal ID { get; set; }
        public string NAMES { get; set; }
        public string SURNAMES { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<decimal> SENIORITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICES { get; set; }
    }
}
