//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypicalSouthernFoods.Web.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesDataModel : DbContext
    {
        public EntitiesDataModel()
            : base("name=EntitiesDataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENTS { get; set; }
        public virtual DbSet<INVOICE> INVOICES { get; set; }
        public virtual DbSet<INVOICES_DET> INVOICES_DET { get; set; }
        public virtual DbSet<RECIPE> RECIPES { get; set; }
        public virtual DbSet<TABLE> TABLES { get; set; }
        public virtual DbSet<WAITER> WAITERS { get; set; }
        public virtual DbSet<VIEW_INVOICES> VIEW_INVOICES { get; set; }
    }
}
