/****** Object:  Table [dbo].[CLIENTS]    Script Date: 6/5/2020 5:35:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAMES] [varchar](60) NULL,
	[SURNAMES] [varchar](60) NULL,
	[ADDRESS] [varchar](100) NULL,
	[PHONE] [varchar](20) NULL,
 CONSTRAINT [CLIENTS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICES]    Script Date: 6/5/2020 5:35:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENT] [int] NULL,
	[ID_TABLE] [int] NULL,
	[ID_WAITER] [int] NULL,
	[INVOICE_DATE] [date] NULL,
 CONSTRAINT [INVOICES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVOICES_DET]    Script Date: 6/5/2020 5:35:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVOICES_DET](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_INVOICE] [int] NULL,
	[RECIPE_NAME] [varchar](60) NULL,
	[PRICE] [int] NULL,
 CONSTRAINT [INVOICES_DET_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TABLES]    Script Date: 6/5/2020 5:35:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TABLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](60) NULL,
	[RESERVED] [char](1) NULL,
	[CHAIRS] [tinyint] NULL,
 CONSTRAINT [TABLES_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WAITERS]    Script Date: 6/5/2020 5:35:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WAITERS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAMES] [varchar](60) NULL,
	[SURNAMES] [varchar](60) NULL,
	[AGE] [tinyint] NULL,
	[SENIORITY] [tinyint] NULL,
 CONSTRAINT [WAITERS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVOICES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICES_CLIENTS] FOREIGN KEY([ID_CLIENT])
REFERENCES [dbo].[CLIENTS] ([ID])
GO
ALTER TABLE [dbo].[INVOICES] CHECK CONSTRAINT [FK_INVOICES_CLIENTS]
GO
ALTER TABLE [dbo].[INVOICES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICES_TABLES] FOREIGN KEY([ID_TABLE])
REFERENCES [dbo].[TABLES] ([ID])
GO
ALTER TABLE [dbo].[INVOICES] CHECK CONSTRAINT [FK_INVOICES_TABLES]
GO
ALTER TABLE [dbo].[INVOICES]  WITH CHECK ADD  CONSTRAINT [FK_INVOICES_WAITERS] FOREIGN KEY([ID_WAITER])
REFERENCES [dbo].[WAITERS] ([ID])
GO
ALTER TABLE [dbo].[INVOICES] CHECK CONSTRAINT [FK_INVOICES_WAITERS]
GO
ALTER TABLE [dbo].[INVOICES_DET]  WITH CHECK ADD  CONSTRAINT [INVOICES_DET_INVOICES] FOREIGN KEY([ID_INVOICE])
REFERENCES [dbo].[INVOICES] ([ID])
GO
ALTER TABLE [dbo].[INVOICES_DET] CHECK CONSTRAINT [INVOICES_DET_INVOICES]
GO
