//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypicalSouthernFoods.Web.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_INVOICES
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<decimal> ID_CLIENT { get; set; }
        public string CLIENTNAME { get; set; }
        public Nullable<decimal> ID_TABLE { get; set; }
        public string TABLENAME { get; set; }
        public Nullable<decimal> ID_WAITER { get; set; }
        public string WAITER { get; set; }
    }
}
